### ISSUE TITLE
Traits break object identity because they are added at class definition time, not runtime

### ISSUE THREAD

**Issue by still-dreaming-1** [mbrowne/dci-php#1]
According to an authoratively sounding commenter under this article, using traits in this way is not true DCI because objects need to have their identity unchanged by their role in order to avoid subtle bugs:
http://thinkmoult.com/a-dci-architecture-implementation-in-php

One alternative to using traits in PHP is to treat it like JavaScript. Just add or set a property to an object dynamically at runtime. Set it to an anonymous function. Unfortunately this requires a special implementation of the __call() magic method in order for it to be callable with the normal method syntax. At one point a I made a generic implementation of __call() that allows you to call these injected methods. I remember it seemed like it had really bad performance in PHP 5, not sure about 7 though.

**Comment by mbrowne** [comment]
Hi, thanks for your interest in doing DCI properly. In the article you linked to, the problem is not with traits per se, but the way they are being used. I think you might be a little unclear about how traits are actually being used in this library...it's actually quite dynamic, and doesn't tie role-playing objects to particular roles at compile-time (but even that wouldn't necessarily break object identity; if you're curious, see the official DCI [C++ examples](http://fulloo.info/Examples/C++Examples/index.html)).

Most implementations that rely on wrappers (i.e. one object wrapping another in order to achieve role binding) are indeed not real DCI, for exactly the reason you mention. But in this library, the role-playing object (the data object) actually wraps the role, rather than the other way around. This means that the identity of the role-playing object is unchanged, and from the perspective of the programmer using the library, it's effectively the same as if the methods were actually injected into the object. I got this idea from a long-time member of the [DCI discussion group](https://groups.google.com/forum/#!forum/object-composition), specifically [this post](https://groups.google.com/d/msg/object-composition/g4BMSdluuC8/ojRjZ9nP8qQJ). James Coplien (DCI co-creator) was initially skeptical but if you read that thread to the end I think you'll see how this is in fact a perfectly valid DCI implementation, and I see no reason it wouldn't work with the [Dijkstra example](http://fulloo.info/Examples/RubyExamples/Dijkstra/) (which relies on consistent object identity).

Of course, using closures as you mention is another solution, and was in fact what I used for my initial DCI implementation in PHP. But you still need a custom `__call()` implementation, as you said. I find the use of closures for this more complex without much benefit, and I'm 99% sure it's less performant (though I haven't benchmarked it). But if you wanted to implement it that way, it could look something like this:

    trait RolePlayer
    {
        protected $methods = array();
 
        public function addMethod($methodName, $methodCallable) {
            if (!is_callable($methodCallable)) {
                throw new InvalidArgumentException("Second parameter must be of type 'callable'");
            }
            $this->methods[$methodName] = Closure::bind($methodCallable, $this, get_class());
        }
    
        public function removeMethod($methodName) {
            unset($this->methods[$methodName]);
        }
    
        //TODO: handle method name conflicts
        public function addRole($traitName) {
            if (trait_exists($traitName)) {
                $className = $traitName.'Class';
                //We need a real class in order to be able to instantiate it,
                //so we can pass the instance to getClosure() below
                if (!class_exists($className)) {
                    eval('class '.$className.' {use '.$traitName.';}');
                }
            }
            elseif (!class_exists($traitName)) {
                throw new InvalidArgumentException("Trait named '$traitName' is not defined");
            }
            else $className = $traitName;
        
            $tmp = new $className;
            $reflClass = new ReflectionClass($tmp);
            $reflMethods = $reflClass->getMethods();
            foreach ($reflMethods as $method) {
                $this->addMethod($method->name, $method->getClosure($tmp));
            }
        }
    
        public function removeRole($traitName) {
            ...
        }
 
        public function __call($methodName, array $args)
        {
            if (isset($this->methods[$methodName])) {
                return call_user_func_array($this->methods[$methodName], $args);
            }
            throw \RuntimeException('There is no method with the given name to call');
        }
    }

Both of these approaches (i.e. closures and the technique I used in this library) have similar downsides:

- Un-binding roles (after a Context method finishes executing, or before invoking a nested Context) has to be done manually. (I did create an [`initSubContext()`](https://github.com/mbrowne/dci-php/blob/master/Context.php#L28) helper method.)

- In order to implement the `__call()` behavior, all objects that might be role players need this functionality somehow. IMO the cleanest solution is to use a `RolePlayer` trait for this, and have all classes for your data objects / potential role players use that trait somewhere in their inheritance hierarchy.

- If you bind a data object to a role that has a method with the same name as one of the methods of the object's data class, then the latter takes precedence (public methods are always called before `___call()` in PHP). You could add a warning for this if you wanted, but it could only be enforced at run-time. In practice this isn't a big deal because DCI programmers should always take care to avoid such name conflicts whenever possible (we came to this conclusion on the group about 2 years ago I think...the potential confusion it causes just doesn't seem to be worth it).

Having said all that, the optimal solution for DCI would arguably be to use source code transformation (transpilation). The main downside of that is that it would require a build step (possibly implemented via a custom PHP extension), but the actual source code transformation technique is simple in principle; you just move the role methods from the roles to the parent Context, and rewrite all calls to the role methods so that they call methods in the Context instead, e.g. `$sourceAccount->withdraw()` would be rewritten to something like `$context->sourceAccount_withdraw()`. That would also open up the possibility of a `role` keyword rather than `trait` as the declaration for the role methods, and many other nice features such as role-object contracts. But the overhead of transpilation is a deterrent, and I'm not working with PHP so much these days so I've chosen not to pursue that. If you're interested in learning more about the technique, you might be interested in checking out my transpilation implementation for Javascript:

https://github.com/mbrowne/babel-dci
http://mbrowne.github.io/babel-dci/

It works quite well except for the fact that Babel doesn't officially support custom syntax plugins (at least not yet), so that part of it is hacky and is currently tied to an older version of Babel's parser. You didn't come here asking about JS, but FYI I recently completed an alternative JS implementation using symbols (to avoid role method name conflicts and the need to worry about unbinding roles), implemented in native ES6 (and with a polyfill for symbols it should work on ES5 also): https://github.com/mbrowne/dci-js-examples/blob/master/TransferMoney/src/TransferMoney.js.

Cheers,
Matt

**Comment by still-dreaming-1** [comment]
Thanks for the info!
